# Generated by Django 3.2.4 on 2021-09-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodmodel',
            name='measure',
            field=models.CharField(choices=[('ШТ', 'Шт.'), ('УПАК', 'Упак.'), ('КОР', 'Кор.')], default=0, max_length=4),
            preserve_default=False,
        ),
    ]
